TRAINING_DATA = [
    ("Arabica coffee beans 1kg", "groceries"),
    ("Robusta coffee beans 500g", "groceries"),
    ("Instant coffee jar 200g", "groceries"),
    ("Green tea bags 100 count", "groceries"),
    ("Basmati rice 5kg", "groceries"),
    ("Brown rice 2kg", "groceries"),
    ("Whole wheat atta 10kg", "groceries"),
    ("Toor dal 1kg", "groceries"),
    ("Chana dal 500g", "groceries"),
    ("Rajma kidney beans 1kg", "groceries"),
    ("Bananas 1 dozen", "groceries"),
    ("Apples shimla 1kg", "groceries"),
    ("Oranges nagpur 2kg", "groceries"),
    ("Tomatoes fresh 1kg", "groceries"),
    ("Onions red 2kg", "groceries"),
    ("Potatoes 3kg", "groceries"),
    ("Spinach bunch fresh", "groceries"),
    ("Milk full cream 1 litre", "groceries"),
    ("Curd fresh 500g", "groceries"),
    ("Paneer fresh 200g", "groceries"),
    ("Butter salted 500g", "groceries"),
    ("Cheese slices 200g", "groceries"),
    ("Eggs 12 count", "groceries"),
    ("Sunflower oil 1 litre", "groceries"),
    ("Mustard oil 500ml", "groceries"),
    ("Ghee pure 500ml", "groceries"),
    ("Sugar refined 1kg", "groceries"),
    ("Jaggery block 500g", "groceries"),
    ("Salt iodised 1kg", "groceries"),
    ("Turmeric powder 200g", "groceries"),
    ("Red chilli powder 100g", "groceries"),
    ("Garam masala 50g", "groceries"),
    ("Cumin seeds 100g", "groceries"),
    ("Wheat bread loaf", "groceries"),
    ("Biscuits marie 300g", "groceries"),
    ("Dark chocolate bar 100g", "groceries"),
    ("Potato chips 150g", "groceries"),
    ("Peanut butter 500g", "groceries"),
    ("Honey organic 500g", "groceries"),
    ("Mixed dry fruits 500g", "groceries"),
    ("Almonds raw 250g", "groceries"),
    ("Cashews roasted 200g", "groceries"),
    ("Oats rolled 1kg", "groceries"),
    ("Cornflakes 500g", "groceries"),
    ("Maggi noodles 12 pack", "groceries"),
    ("Pasta penne 500g", "groceries"),
    ("Tomato ketchup 1kg", "groceries"),
    ("Soy sauce 200ml", "groceries"),
    ("Mineral water 20 litre", "groceries"),
    ("Orange juice 1 litre", "groceries"),

    ("Dish soap 500ml", "household"),
    ("Dishwashing liquid refill 1 litre", "household"),
    ("Laundry detergent powder 2kg", "household"),
    ("Fabric softener 1 litre", "household"),
    ("Floor cleaner phenyl 1 litre", "household"),
    ("Toilet cleaner 500ml", "household"),
    ("Glass cleaner spray 500ml", "household"),
    ("Bathroom cleaner 750ml", "household"),
    ("Paper towels 6 rolls", "household"),
    ("Toilet paper 12 rolls", "household"),
    ("Tissue box 200 sheets", "household"),
    ("Garbage bags large 30 count", "household"),
    ("Aluminium foil 25m", "household"),
    ("Cling film wrap 30m", "household"),
    ("Scrub pad pack of 5", "household"),
    ("Microfibre cleaning cloth", "household"),
    ("Broom soft bristle", "household"),
    ("Mop with bucket", "household"),
    ("Dustpan plastic", "household"),
    ("Bathroom mat rubber", "household"),
    ("Laundry basket plastic", "household"),
    ("Clothes hangers 20 pack", "household"),
    ("Storage container set plastic", "household"),
    ("Mosquito repellent liquid", "household"),
    ("Cockroach killer spray", "household"),
    ("Air freshener lavender", "household"),
    ("Naphthalene balls 200g", "household"),
    ("Hand wash refill 750ml", "household"),
    ("Bath soap 4 pack", "household"),
    ("Shampoo 650ml", "household"),
    ("Toothpaste 200g", "household"),
    ("Toothbrush pack of 4", "household"),
    ("Shaving razor cartridge", "household"),
    ("Face towel cotton", "household"),
    ("Bed sheet double cotton", "household"),
    ("Pillow cover pair", "household"),
    ("Candles pack of 6", "household"),
    ("Matchbox pack of 10", "household"),
    ("Sewing kit basic", "household"),
    ("Umbrella folding", "household"),

    ("Espresso machine", "appliances"),
    ("Electric kettle 1.7L", "appliances"),
    ("Coffee grinder burr type", "appliances"),
    ("Microwave oven 20 litre", "appliances"),
    ("Refrigerator double door", "appliances"),
    ("Washing machine front load", "appliances"),
    ("Air conditioner 1.5 ton", "appliances"),
    ("Ceiling fan 1200mm", "appliances"),
    ("Table fan 400mm", "appliances"),
    ("Room heater fan type", "appliances"),
    ("Water purifier RO", "appliances"),
    ("Mixer grinder 750W", "appliances"),
    ("Food processor 800W", "appliances"),
    ("Hand blender 300W", "appliances"),
    ("Induction cooktop 2000W", "appliances"),
    ("Electric rice cooker 1.8L", "appliances"),
    ("Sandwich toaster 750W", "appliances"),
    ("Air fryer 4 litre", "appliances"),
    ("Vacuum cleaner 1400W", "appliances"),
    ("Steam iron 1600W", "appliances"),
    ("Geyser water heater 15L", "appliances"),
    ("Dishwasher 12 place", "appliances"),
    ("Chimney kitchen 60cm", "appliances"),
    ("Juicer centrifugal 500W", "appliances"),
    ("Electric pressure cooker", "appliances"),

    ("AA batteries 4 pack", "electronics"),
    ("AAA batteries 8 pack", "electronics"),
    ("Rechargeable battery pack", "electronics"),
    ("USB cable type C 1m", "electronics"),
    ("HDMI cable 2m", "electronics"),
    ("Phone charger 20W adapter", "electronics"),
    ("Power bank 10000mAh", "electronics"),
    ("Extension board 4 socket", "electronics"),
    ("LED bulb 9W", "electronics"),
    ("LED tube light 20W", "electronics"),
    ("Wireless mouse", "electronics"),
    ("Mechanical keyboard", "electronics"),
    ("Laptop stand aluminium", "electronics"),
    ("Webcam 1080p", "electronics"),
    ("Bluetooth speaker portable", "electronics"),
    ("Wired earphones 3.5mm", "electronics"),
    ("Wireless earbuds", "electronics"),
    ("Over ear headphones", "electronics"),
    ("Smartwatch fitness band", "electronics"),
    ("Memory card 128GB", "electronics"),
    ("Pen drive 64GB", "electronics"),
    ("External hard disk 1TB", "electronics"),
    ("Wifi router dual band", "electronics"),
    ("Set top box HD", "electronics"),
    ("Mobile phone case silicone", "electronics"),
    ("Screen protector tempered glass", "electronics"),
    ("Tripod stand mobile", "electronics"),
    ("Ring light 10 inch", "electronics"),
    ("Digital thermometer", "electronics"),
    ("Calculator scientific", "electronics"),
]

CATEGORIES = sorted({label for _, label in TRAINING_DATA})